language: scala
sudo: required
dist: trusty

scala:
  - 2.11.12
  - 2.12.5

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

before_install:
  - pip install --user codecov

script:
  - sbt +test
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)